apiVersion: v1
kind: Service
metadata:
  name: kemployee
spec:
  selector:
    app: kemployee
  ports:
    - port: 8888
      targetPort: 8888
  type: NodePort
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kemployee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kemployee
  template:
    metadata:
      labels:
        app: kemployee
    spec:
      containers:
        - name: app
          image: devopsedu/employee
          ports:
            - containerPort: 8888
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always