# This is to create nginx docker container
# create namespaece + mynginx pod + NodePOrt service
kind: Namespace
apiVersion: v1
metadata:
  name: nsmyng
  labels:
    name: myng
---
apiVersion: v1
kind: Service
metadata:
  
  name: svcmyngnprt
  namespace: nsmyng
spec:
  type: NodePort
  selector:
    app: myng
  ports:
  - name: httpport
    port: 8080
    targetPort: 80
    nodePort: 30080
  - name: heatlhport
    port: 9090
    targetPort: 90
    nodePort: 30090
    
---
apiVersion: v1
kind: Pod
metadata:
  name: webprod02
  namespace: nsmyng
  labels:
    name: myng
spec:
  containers:
  - name: mynginx
    image: connectamitgupta/mynginx:latest
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
